from .benchmark import benchmark_callable
from .empirical import (
    additive_kernel,
    block_trace_ratios,
    frobenius_rbf_kernel,
    linear_empirical_kernel,
    mixed_empirical_kernel,
    polynomial_empirical_kernel,
    temporal_feature_matrix,
)
from .factors import DenseCholeskyFactor, SparseInverseFactor
from .gauss_newton import gauss_newton_matrices, solve_gauss_newton, weighted_norm_squared
from .kernels import (
    matern52_1d,
    matern52_2d,
    matern52_2d_dx1,
    matern52_2d_dx1dy1,
    matern52_2d_dx1dy2,
    matern52_2d_dx2,
    matern52_2d_dx2dy1,
    matern52_2d_dx2dy2,
    matern52_2d_dy1,
    matern52_2d_dy2,
    matern52_2d_laplace_x,
    matern52_2d_laplace_x_dy1,
    matern52_2d_laplace_x_dy2,
    matern52_2d_laplace_xy,
    matern52_2d_laplace_y,
    matern52_2d_laplace_y_dx1,
    matern52_2d_laplace_y_dx2,
)
from .ordering import MeasurementOrdering, build_measurement_ordering, maximin
from .pde_baselines import (
    AllenCahnCNConfig,
    BurgersCNConfig,
    build_allen_cahn_flattened_coordinates,
    burgers_crank_nicolson_dataset,
    burgers_crank_nicolson_rollout,
    generate_allen_cahn_initial_condition,
    generate_burgers_initial_condition,
    solve_allen_cahn_crank_nicolson,
)
from .sparse_cholesky import build_sparsity_pattern, sparse_precision_factor

__all__ = [
    "AllenCahnCNConfig",
    "BurgersCNConfig",
    "DenseCholeskyFactor",
    "MeasurementOrdering",
    "SparseInverseFactor",
    "additive_kernel",
    "benchmark_callable",
    "block_trace_ratios",
    "build_allen_cahn_flattened_coordinates",
    "build_measurement_ordering",
    "build_sparsity_pattern",
    "burgers_crank_nicolson_dataset",
    "burgers_crank_nicolson_rollout",
    "frobenius_rbf_kernel",
    "gauss_newton_matrices",
    "generate_allen_cahn_initial_condition",
    "generate_burgers_initial_condition",
    "linear_empirical_kernel",
    "matern52_1d",
    "matern52_2d",
    "matern52_2d_dx1",
    "matern52_2d_dx1dy1",
    "matern52_2d_dx1dy2",
    "matern52_2d_dx2",
    "matern52_2d_dx2dy1",
    "matern52_2d_dx2dy2",
    "matern52_2d_dy1",
    "matern52_2d_dy2",
    "matern52_2d_laplace_x",
    "matern52_2d_laplace_x_dy1",
    "matern52_2d_laplace_x_dy2",
    "matern52_2d_laplace_xy",
    "matern52_2d_laplace_y",
    "matern52_2d_laplace_y_dx1",
    "matern52_2d_laplace_y_dx2",
    "maximin",
    "mixed_empirical_kernel",
    "polynomial_empirical_kernel",
    "solve_allen_cahn_crank_nicolson",
    "solve_gauss_newton",
    "sparse_precision_factor",
    "temporal_feature_matrix",
    "weighted_norm_squared",
]
