from .benchmark import benchmark_callable
from .empirical import (
    additive_kernel,
    block_trace_ratios,
    frobenius_rbf_kernel,
    linear_empirical_kernel,
    mixed_empirical_kernel,
    polynomial_empirical_kernel,
    temporal_feature_matrix,
)
from .factors import DenseCholeskyFactor, SparseInverseFactor, dense_precision_factor
from .gauss_newton import (
    ConjugateGradientResult,
    GaussNewtonLinearization,
    ResidualOperator,
    gauss_newton_linearization,
    gauss_newton_matrices,
    solve_gauss_newton,
    weighted_norm_squared,
)
from .kernels import (
    matern52_1d,
    matern52_2d,
    matern52_2d_dx1,
    matern52_2d_dx1dy1,
    matern52_2d_dx1dy2,
    matern52_2d_dx2,
    matern52_2d_dx2dy1,
    matern52_2d_dx2dy2,
    matern52_2d_dy1,
    matern52_2d_dy2,
    matern52_2d_laplace_x,
    matern52_2d_laplace_x_dy1,
    matern52_2d_laplace_x_dy2,
    matern52_2d_laplace_xy,
    matern52_2d_laplace_y,
    matern52_2d_laplace_y_dx1,
    matern52_2d_laplace_y_dx2,
)
from .navier_stokes import (
    NavierStokesFactorBundle,
    PrecomputedStreamfunctionOperator,
    build_navier_stokes_factors,
    compute_streamfunction_feature_bank,
    evaluate_streamfunction_kernel,
    precompute_streamfunction_operator,
    rollout_navier_stokes_krom,
    solve_streamfunction_with_fft,
    solve_streamfunction_with_kernel,
    streamfunction_poisson_residual_and_jacobian,
)
from .ordering import MeasurementOrdering, build_measurement_ordering, maximin
from .pde_baselines import (
    AllenCahnCNConfig,
    BurgersCNConfig,
    NSVorticityConfig,
    build_allen_cahn_flattened_coordinates,
    burgers_crank_nicolson_dataset,
    burgers_crank_nicolson_rollout,
    compute_energy_spectrum,
    compute_velocity_from_vorticity,
    generate_allen_cahn_initial_condition,
    generate_burgers_initial_condition,
    generate_ns_vorticity_initial_condition,
    navier_stokes_vorticity_dataset,
    navier_stokes_vorticity_rollout,
    ns_vorticity_grid,
    solve_allen_cahn_crank_nicolson,
)
from .sparse_cholesky import build_sparsity_pattern, sparse_precision_factor
from .sweeps import SweepResult, plot_sweep_result, run_comparison_sweep
from .workflows import (
    KernelAssembly,
    allen_cahn_residual_and_jacobian,
    allen_cahn_residual_operator,
    build_allen_cahn_empirical_theta,
    build_burgers_empirical_theta,
    build_burgers_matern_theta,
    build_elliptic_empirical_theta,
    build_elliptic_matern_theta,
    build_navier_stokes_empirical_theta,
    build_navier_stokes_matern_theta,
    burgers_residual_and_jacobian,
    burgers_residual_operator,
    darcy_residual_and_jacobian,
    darcy_residual_operator,
    elliptic_residual_and_jacobian,
    elliptic_residual_operator,
    navier_stokes_vorticity_residual_and_jacobian,
    navier_stokes_vorticity_residual_operator,
)
